# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nit',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='razon_social',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
