# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nit', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo_media')),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('activo_inactivo', models.BooleanField()),
            ],
        ),
    ]
