# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
