# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20170420_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'logo_media'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.IntegerField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=12),
        ),
    ]
