# -*- encoding:utf-8 -*-
from django import forms

from .models import Vehiculo


class VehiculoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(VehiculoForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['placa'].widget.attrs['readonly'] = True

    def clean_placa(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.placa
        else:
            return self.cleaned_data['placa']

    class Meta:
        model = Vehiculo

        fields = [
                'placa',
                'conductorDefault',
                'numeroInterno',
                'combustible',
                'foto',
                'numLicenciaTransito',
                'docLicenciaTransito',
                'organismoTransito',
                'fechaExpedicion',
                'marca',
                'linea',
                'cilindraje',
                'modelo',
                'claseVehiculo',
                'color',
                'tipoServicio',
                'carroceria',
                'capacidad',
                'numMotor',
                'numChasis',
                'propietario',
                'idPropietario',
                'numTarjetaOperacion',
                'docTO',
                'fechaInicioTo',
                'fechaVencimientoTo',
                'empresaAfiliado',
                'idEmpresaAfiliado',
                'numSoat',
                'docSoat',
                'fechaInicioSoat',
                'fechaVencimientoSoat',
                'aseguradoraSoat',
                'numCertificadoRtm',
                'docRtm',
                'fechaInicioRtm',
                'fechaVencimientoRtm',
                'cda',
                'numeroPolizasRce_Rcc',
                'docPolizasRce_Rcc',
                'fechaInicioRce_Rcc',
                'fechaVencimientoRce_Rcc',
                'aseguradoraRce_Rcc',
        ]
        labels = {
            'placa': 'Placa',
            'conductorDefault': 'Conductor por defecto',
            'numeroInterno': 'Numero Interno',
            'combustible': 'Tipo de combustible',
            'foto': 'Foto',
            'numLicenciaTransito': 'Numero de licencia transito',
            'docLicenciaTransito': 'Archivo PDF',
            'organismoTransito': 'Organismo de transito',
            'fechaExpedicion': 'Fecha de expedición',
            'marca': 'Marca',
            'linea': 'Linea',
            'cilindraje': 'Cilindraje',
            'modelo': 'Modelo',
            'claseVehiculo': 'Clase de vehiculo',
            'color': 'Color',
            'tipoServicio': 'Tipo de servicio',
            'carroceria': 'Tipo Carroceria',
            'capacidad': 'Capacidad',
            'numMotor': 'Numero de motor',
            'numChasis': 'Numero de chasis',
            'propietario': 'Nombre propietario',
            'idPropietario': 'Identificacion propietario',
            'numTarjetaOperacion': 'Numero tarjeta de operacion',
            'docTO': 'Archivo PDF',
            'fechaInicioTo': 'Fecha de expedicion',
            'fechaVencimientoTo': 'Fecha de vencimiento',
            'empresaAfiliado': 'Empresa afiliado',
            'idEmpresaAfiliado': 'Nit empresa afiliado',
            'numSoat': 'Numero de SOAT',
            'docSoat': 'Archivo PDF',
            'fechaInicioSoat': 'Fecha de expedicion',
            'fechaVencimientoSoat': 'Fecha de vencimiento',
            'aseguradoraSoat': 'Aseguradora',
            'numCertificadoRtm': 'Numero de revision tecnico mecanica',
            'docRtm': 'Archivo PDF',
            'fechaInicioRtm': 'Fecha de expedicion',
            'fechaVencimientoRtm': 'Fecha de expedicion',
            'cda': 'Centro de diagnostico Automotriz',
            'numeroPolizasRce_Rcc': 'Numero de Polizas Rcc y Rce',
            'docPolizasRce_Rcc': 'Archivo PDF',
            'fechaInicioRce_Rcc': 'Fecha de expedicion',
            'fechaVencimientoRce_Rcc': 'Fecha de vencimiento',
            'aseguradoraRce_Rcc': 'Aseguradora',
        }
        widgets = {
            'placa': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '6', 'data-error': 'Ingrese la placa del vehiculo'}),
            'conductorDefault': forms.TextInput(),
            'numeroInterno': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '6', 'data-error': 'Ingrese el numero interno del vehiculo'}),
            'combustible': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese tipo de combustible'}),
            'foto': forms.FileInput(),
            'numLicenciaTransito': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese numero de licencia de transito'}),
            'docLicenciaTransito': forms.FileInput(),
            'organismoTransito': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese organismo de transito'}),
            'fechaExpedicion': forms.DateInput(),
            'marca': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese marca del vehiculo'}),
            'linea': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese linea del vehiculo'}),
            'cilindraje': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese cilindraje del vehiculo'}),
            'modelo': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '4', 'data-error': 'Ingrese modelo del vehiculo'}),
            'claseVehiculo': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese la clase del vehiculo'}),
            'color': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese color del vehiculo'}),
            'tipoServicio': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese tipo de servicio del vehiculo'}),
            'carroceria': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese tipo de carroceria del vehiculo'}),
            'capacidad': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '2', 'data-error': 'Ingrese la capacidad del vehiculo'}),
            'numMotor': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese el numero de motor del vehiculo'}),
            'numChasis': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese el numero de chasis del vehiculo'}),
            'propietario': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese propietario del vehiculo'}),
            'idPropietario': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese identificacion de propietario del vehiculo'}),
            'numTarjetaOperacion': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese el numero de tarjeta de operacion'}),
            'docTO': forms.FileInput(),
            'fechaInicioTo': forms.DateInput(),
            'fechaVencimientoTo': forms.DateInput(),
            'empresaAfiliado': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese empresa a la que se encuentra afiliado el vehiculo'}),
            'idEmpresaAfiliado': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese identificacion de la empresa afiliadora'}),
            'numSoat': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese el numero de SOAT del vehiculo'}),
            'docSoat': forms.FileInput(),
            'fechaInicioSoat': forms.DateInput(),
            'fechaVencimientoSoat': forms.DateInput(),
            'aseguradoraSoat': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese la aseguradora que expide el SOAT'}),
            'numCertificadoRtm': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese el numero de la revision tecnicomecanica'}),
            'docRtm': forms.FileInput(),
            'fechaInicioRtm': forms.DateInput(),
            'fechaVencimientoRtm': forms.DateInput(),
            'cda': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese el centro de diagnostico automotriz'}),
            'numeroPolizasRce_Rcc': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese en numero de las polizas del vehiculo'}),
            'docPolizasRce_Rcc': forms.FileInput(),
            'fechaInicioRce_Rcc': forms.DateInput(),
            'fechaVencimientoRce_Rcc': forms.DateInput(),
            'aseguradoraRce_Rcc': forms.TextInput(attrs={'class': 'form-control', 'data-error': 'Ingrese la aseguradora que expide las polizas'}),
        }
